#!/usr/bin/env bash

# i3 screen lock script
#
# requires:
#  scrot
#  imagemagick
#  i3

icon="$HOME/.unixrc/lock-icon.png"
tmpbg="/tmp/wall.png"

(( $# )) && { icon=$1; }

scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"

i3lock -i "$tmpbg"
