#!/usr/bin/env bash

# a script that randomly selects a JPG file from a directory and sets it as the
# desktop background

# requires:
#  feh

# directory to select wallpaper from
WALLPAPER_DIR="$HOME/wallpapers"

if [ ! -d "$WALLPAPER_DIR/" ]; then
  logger "no wallpaper directory"
  exit 1
fi

# randomly select an image from the directory
WALLPAPER=$(\ls "$WALLPAPER_DIR"/*{.jpg,.png} | shuf -n1)

# set the selected image as the desktop wallpaper
if command -v feh > /dev/null 2>&1; then
  /usr/bin/feh --bg-center "$WALLPAPER"
  exit 0
else
  logger "feh is not installed, try apt-get install feh"
  exit 1
fi

