#!/usr/bin/env bash

internal="eDP"
left="DisplayPort-1"
right="DisplayPort-0"

$HOME/.unixrc/scripts/xrandr-multi-monitor-setup.sh $internal $left $right;
i3-msg restart;
$HOME/.unixrc/i3-scripts/set-wallpaper;

# set keyboard autorepeat rate
xset r rate 200 30
