#!/usr/bin/env bash

internal="eDP"

external=`xrandr | grep -E "\S+-[[:digit:]] connected" \
                 | sed -E 's/(\S+-[[:digit:]]) connected.*/\1/'`

if [[ ! -z "$external" ]]; then
  xrandr --dpi 109 --output "$internal" --off --output "$external" --auto --primary
  i3-msg restart;
  "$HOME/.dot-files/i3-scripts/set-wallpaper";
  touch "$HOME/.docked";
fi

# set keyboard autorepeat rate
xset r rate 200 30
