#!/usr/bin/env bash

# i3 screen lock script
#
# requires:
#  scrot
#  imagemagick
#  i3

# log file location
# ENV_LOG="$HOME/env.log"

ts() { printf '%s\t%s\t\n' "$(date)" "$*"; }

envlog() {
  if [ -z ${ENV_LOG+x} ]; then
    logger "$@";
  else
    ts >> "$ENV_LOG" "$@"
  fi
}

if ! command -v scrot >/dev/null 2>&1; then
  envlog "scrot is not installed, try apt-get install scrot";
  exit 1;
fi

if ! command -v convert >/dev/null 2>&1; then
  envlog "imagemagic/convert is not installed, try apt-get install imagemagick";
  exit 1;
fi

# location to store our blurred screenshot
tmpbg="/tmp/lock-screen.png"

generate_lock_screen() {
  # icon that is displayed when screen is locked
  local __icon="$HOME/.unixrc/i3-lock-icon.png"
  # Take a screenshot
  scrot "$tmpbg"
  # make it blurry
  convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
  # place the lock icon over the screenshot
  convert "$tmpbg" "$__icon" -gravity center -composite -matte "$tmpbg"
}

# lock the screen
generate_lock_screen
i3lock -i "$tmpbg"

# Turn the screen off after a delay
sleep 60; pgrep i3lock && xset dpms force off;
