#!/usr/bin/env bash

internal="eDP"
dp0="DisplayPort-0"
dp1="DisplayPort-1"
hdmi="HDMI-0"

xrandr --dpi 192 --output "$internal" --mode 2880x1800 --primary \
       --output "$dp0" --off \
       --output "$dp1" --off\
       --output "$hdmi" --off

i3-msg restart;
$HOME/.unixrc/i3-scripts/set-wallpaper;

rm -f "$HOME/.docked"

# set keyboard autorepeat rate
xset r rate 200 30
