#!/usr/bin/env bash

# completely detached from terminal

readonly regex="resolution:[[:space:]]*([0-9]+)x[0-9]+"
xdpyinfo_output="$(xdpyinfo)"

declare dpi

if [[ $xdpyinfo_output =~ $regex ]]; then
  dpi="${BASH_REMATCH[1]}"
  if [[ $((dpi)) -eq 192 ]]; then
    export GDK_SCALE=2; 
  fi
else
  printf "No matches found\n"
fi

if [ $# -gt 0 ]; then
  nohup /usr/lib/firefox/firefox.sh "$1" </dev/null >/dev/null 2>&1 &
else
  nohup /usr/lib/firefox/firefox.sh </dev/null >/dev/null 2>&1 &
fi
