#!/bin/bash

dot_file_repo_dir="$HOME/.dot-files"
shell_cfgs_dir="$dot_file_repo_dir/shell-configs"
banner="****************************************"

copy_dot_file() {
  copy_src="$1"
  copy_dest="$2"
  echo "$banner"

  if [ -f "$copy_dest" ] && [ ! -L "$copy_dest" ]; then
    echo "Backing up $copy_dest";
    mv "$copy_dest" "$copy_dest".orig.bak;
    echo "Creating copy $copy_dest";
    cp "$copy_src" "$copy_dest"
  elif [ ! -f "$copy_dest" ]; then
    echo "Creating copy $copy_dest";
    cp "$copy_src" "$copy_dest"
  fi
  echo ""
}

__call_ln() {
  declare -r link_dest="$1"
  declare -r link_src="$2"
  ln --symbolic --relative "$link_src" "$link_dest"
}

__create_link() {
  declare -r link_dest="$1"
  declare -r link_src="$2"
  echo "$banner"

  if [ -e "$link_dest" ] && [ ! -L "$link_dest" ]; then
    local idx=0
    local suffix=".bak"
    while test -e "$link_dest$suffix"; do
      (( ++idx ))
      suffix="$(printf '.bak.%d' "$idx")"
    done

    echo "Backing up $link_dest to $link_dest$suffix";
    mv "$link_dest" "$link_dest$suffix";

    echo "Creating link: $link_dest -> $link_src"
    __call_ln "$link_dest" "$link_src"
  elif [ -L "$link_dest" ]; then
    echo "Updating link: $link_dest -> $link_src"
    unlink "$link_dest"
    __call_ln "$link_dest" "$link_src"
  elif [ ! -e "$link_dest" ]; then
    echo "Creating link: $link_dest -> $link_src"
    __call_ln "$link_dest" "$link_src"
  fi
  echo ""
}

#################################################################
## Rename the repository directory name to a dotfile           ##
#################################################################
if [ -d "$HOME/dot-files" ]; then
  echo "Moving $HOME/dot-files to $dot_file_repo_dir"
  mv "$HOME/dot-files" "$dot_file_repo_dir"
fi

if [ -d "$dot_file_repo_dir" ]; then
  echo "initializing dot file git submodules"
  cd "$dot_file_repo_dir"
  git submodule init
  git submodule update
fi

if [ -f "$shell_cfgs_dir/base16-shell/profile_helper.sh" ]; then
  echo "initializing base16 profiles";
  source "$shell_cfgs_dir/base16-shell/profile_helper.sh"
fi

#################################################################
## link in our grep-ackrc file                                 ##
#################################################################
__create_link "$HOME/.ackrc" "$dot_file_repo_dir/ack.ackrc"

#################################################################
## link in our bashrc file                                     ##
#################################################################
__create_link "$HOME/.bashrc" "$shell_cfgs_dir/bashrc.bash"

#################################################################
## link in our zshrc file                                      ##
#################################################################
__create_link "$HOME/.zshrc" "$shell_cfgs_dir/zshrc.zsh"

#################################################################
## link in our xinitrc file                                    ##
#################################################################
__create_link "$HOME/.xinitrc" "$dot_file_repo_dir/xinit.xinitrc"
copy_dot_file "$dot_file_repo_dir/xinit.local" "$HOME/.xinitrc-local"

#################################################################
## link in our vimrc file                                      ##
#################################################################
__create_link "$HOME/.vimrc" "$dot_file_repo_dir/vim.vimrc"

#################################################################
## link in our vim directory                                   ##
#################################################################
__create_link "$HOME/.vim" "$dot_file_repo_dir/vim.d"

#################################################################
## link in our urxvt configs                                   ##
#################################################################
  __create_link "$HOME/.Xresources" "$dot_file_repo_dir/Xresources.Xresources"
  __create_link "$HOME/.urxvt" "$dot_file_repo_dir/urxvt-configs"

#################################################################
## link in our gitconfig file                                  ##
#################################################################
__create_link "$HOME/.gitconfig" "$dot_file_repo_dir/git.config"

#################################################################
## link in our valgrindrc file                                 ##
#################################################################
__create_link "$HOME/.valgrindrc" "$dot_file_repo_dir/valgrind.valgrindrc"

#################################################################
## Get rid of annoying default directories                     ##
#################################################################
if [ -f "$HOME/.config/user-dirs.dirs" ]; then
  sed -i 's/^\(XDG_TEMPLATES_DIR=\)\"\$HOME\/\(Templates\)\"$/\1\"\/tmp\/\2\"/' \
    $HOME/.config/user-dirs.dirs

  sed -i 's/^\(XDG_PUBLICSHARE_DIR=\)\"\$HOME\/\(Public\)\"$/\1\"\/tmp\/\2\"/' \
    $HOME/.config/user-dirs.dirs

  sed -i 's/^\(XDG_MUSIC_DIR=\)\"\$HOME\/\(Music\)\"$/\1\"\/tmp\/\2\"/' \
    $HOME/.config/user-dirs.dirs

  sed -i 's/^\(XDG_PICTURES_DIR=\)\"\$HOME\/\(Pictures\)\"$/\1\"\/tmp\/\2\"/' \
    $HOME/.config/user-dirs.dirs

  sed -i 's/^\(XDG_VIDEOS_DIR=\)\"\$HOME\/\(Videos\)\"$/\1\"\/tmp\/\2\"/' \
    $HOME/.config/user-dirs.dirs
fi

#################################################################
## Move the existing annoying default directories to tmp       ##
#################################################################
if [ -d "$HOME/Templates" ]; then
  echo "Moving $HOME/Templates to /tmp/Templates"
  mv "$HOME/Templates" "/tmp/Templates"
fi

if [ -d "$HOME/Public" ]; then
  echo "Moving $HOME/Public to /tmp/Public"
  mv "$HOME/Public" "/tmp/Public"
fi

if [ -d "$HOME/Music" ]; then
  echo "Moving $HOME/Music to /tmp/Music"
  mv "$HOME/Music" "/tmp/Music"
fi

if [ -d "$HOME/Pictures" ]; then
  echo "Moving $HOME/Pictures to /tmp/Pictures"
  mv "$HOME/Pictures" "/tmp/Pictures"
fi

if [ -d "$HOME/Videos" ]; then
  echo "Moving $HOME/Videos to /tmp/Videos"
  mv "$HOME/Videos" "/tmp/Videos"
fi

#################################################################
## Remove stupid 'examples.desktop' file                       ##
#################################################################
rm -rf "$HOME/examples.desktop"

exit 0

