#!/usr/bin/env bash

razer_id='Razer Razer DeathAdder'
prop_id="libinput Accel Speed"

if [ -f "$HOME/.dot-files/shell-configs/logger.bash" ]; then
  source "$HOME/.dot-files/shell-configs/logger.bash";
fi

me=`basename "$0"`

xinput --set-prop "$razer_id" "$prop_id" -0.9

if [ "$?" -eq 0 ]; then
  envlog "[$me]: xinput succeeded"
else
  envlog "[$me]: xinput failed"
fi
