#!/usr/bin/env bash

##
## check for a valid device file on the cli
##
if test "$#" -lt 1; then
  echo "USAGE: kermitwrapper <device file> (e.g. kermitwrapper /dev/ttyUSB0)" 1>&2
  exit -1
fi

if [[ $1 == "cdh" ]]; then
  device_name=/dev/cdh-flight-console;
  device_path="$(readlink -f $device_name)";
elif [[ $1 == "adc" ]]; then
  device_name=/dev/adc-flight-console;
  device_path="$(readlink -f $device_name)";
else
  device_name="$1";
  device_path="$device_name";
fi


if test ! -e "$device_path"; then
  echo -n "[`basename "$0"`]: No such device file: \'$device_name\'.";
  echo "Is it plugged in?";
  exit -1;
fi


##
## check if the device is locked
##
device="${device_path##*/}"
lock_file="/var/lock/LCK..$device"
if test -e "$lock_file"; then

  ## trim any whitespace
  pid="$(echo -e "$(cat $lock_file)" | tr -d '[[:space:]]')"

  ## check if the locking process is still running
  if test $(kill -s 0 $pid &> /dev/null); then
    echo "$device_path is locked by $pid"
    exit -1
  fi
fi

## make a kermrc file with a random suffix
rand="$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32)"
kermit_file="/tmp/kermrc_$rand"

echo "set line $device_path" > "$kermit_file";
echo "set speed 115200" >> "$kermit_file";
echo "set parity none" >> "$kermit_file";
echo "set carrier-watch off" >> "$kermit_file";
echo "set flow-control none" >> "$kermit_file";
echo "connect" >> "$kermit_file";
sleep 0.1;
/usr/bin/kermit -l "$device_path" -y "$kermit_file";
rm -f "$kermit_file";

exit 0
