#!/usr/bin/env bash

bin="/usr/bin"

sudo update-alternatives --remove cc  "$bin/gcc-4.9"
sudo update-alternatives --remove cc  "$bin/gcc-5"
sudo update-alternatives --remove cc  "$bin/clang-3.8"
sudo update-alternatives --remove clang  "$bin/clang-3.8"
