#!/usr/bin/env bash

bin="/usr/bin"

sudo update-alternatives --install "$bin/cc"  cc  "$bin/gcc-4.9" 100 \
                         --slave   "$bin/gcc" gcc "$bin/gcc-4.9" \
                         --slave   "$bin/c++" c++ "$bin/g++-4.9" \
                         --slave   "$bin/g++" g++ "$bin/g++-4.9"

sudo update-alternatives --install "$bin/cc"  cc  "$bin/gcc-5" 100 \
                         --slave   "$bin/gcc" gcc "$bin/gcc-5" \
                         --slave   "$bin/c++" c++ "$bin/g++-5" \
                         --slave   "$bin/g++" g++ "$bin/g++-5"

sudo update-alternatives --install "$bin/cc"  cc  "$bin/clang-3.8" 100 \
                         --slave   "$bin/c++" c++ "$bin/clang++-3.8" \
                         --slave   "$bin/g++" g++ "$bin/clang++-3.8"

# sudo update-alternatives --install "$bin/clang"   clang   "$bin/clang-3.8" 100 \
#                          --slave   "$bin/clang++" clang++ "$bin/clang++-3.8" \
